[package]
name = "common"
version = "1.0.0"
edition = "2021"
description = "Common utilities and definitions for the passkeeper application."
authors = ["Kwangsoo Seo", "monoslab <chps74@naver.com>"]